apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-config"
data:
  DATABASE_HOST: "{{ .Values.config.database_host }}"
  DATABASE_PORT: "{{ .Values.config.database_port }}"
  DATABASE_NAME: "{{ .Values.config.database_name }}"
  DATABASE_USER: "{{ .Values.config.database_user }}"
  DATABASE_PASSWORD: "{{ .Values.config.database_password }}"
