image:
  repository: ghcr.io/prod-legit/deepcity_backend
  tag: "latest"
  pullPolicy: IfNotPresent

imagePullSecrets: []

ingress:
  enabled: false
  clusterIssuer: letsencrypt-prod
  path: /
  domain: example.com
  tlsSecretName: ""

config:
  database_host: localhost
  database_port: 5432
  database_name: app
  database_user: user
  database_password: password
